### ISSUE TITLE
Broken Settler

### ISSUE THREAD

**Issue by zippyzap** [ataranlen/civcraft#66] opened 2016-11-22 18:34 UTC
went to place down my settler followed all the steps and when i went to accept it into my civ it said to contact a admin.

**Comment by zippyzap** [comment] 2016-11-22 18:36
Got it to work but the name is messed up now any way you can change it to the name it should be?     The name it is now is asf and it should have been Ryza could you please fix it?

**Comment by ataranlen** [comment] 2016-11-22 18:46
Your civ already has another town named Ryza.

**Comment by ataranlen** [comment] 2016-11-22 18:48
Not sure what happened, but there are two town records. One for Ryza and one for asf. I'll investigate.

**Comment by zippyzap** [comment] 2016-11-22 18:49
ok well Ryza never got made i got dced in the middle of trying to make it

**Comment by ataranlen** [comment] 2016-11-22 18:50
That information would have been relevant in the original bug report....

**Comment by zippyzap** [comment] 2016-11-22 18:50
my bad

**Comment by ataranlen** [comment] 2016-11-22 18:51
Duplicate of #46

**Closed as completed by ataranlen** 2016-11-22 18:51 UTC
